baseURL = 'https://veranijmeijer.github.io/socialdata/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "meme"
publishDir = "docs"
sectionPagesMenu = "main"
[markup.goldmark.renderer]
  unsafe = true
